Support WSL (based on c8beea7) (#8)

diff --git a/common/rootfs_supervisor/usr/bin/supervisor_bootstrap b/common/rootfs_supervisor/usr/bin/supervisor_bootstrap
--- a/common/rootfs_supervisor/usr/bin/supervisor_bootstrap
+++ b/common/rootfs_supervisor/usr/bin/supervisor_bootstrap
@@ -5,6 +5,12 @@ set -e
 rm /etc/machine-id
 dbus-uuidgen --ensure=/etc/machine-id
 
+if grep -q 'microsoft-standard|standard-WSL' /proc/version; then
+    # The docker daemon does not start when running WSL2 without adjusting iptables
+    update-alternatives --set iptables /usr/sbin/iptables-legacy || echo "Fails adjust iptables"
+    update-alternatives --set ip6tables /usr/sbin/iptables-legacy || echo "Fails adjust ip6tables"
+fi
+
 service docker start
 
 chmod +x /usr/bin/ha
