Add multiarch support for cas, shellcheck and os-agent

diff --git a/common/install/cas b/common/install/cas
--- a/common/install/cas
+++ b/common/install/cas
@@ -2,19 +2,20 @@
 
 set -e
 
-apt-get update
-apt-get install -y --no-install-recommends \
-    apt-transport-https \
-    ca-certificates \
-    curl \
-    software-properties-common \
-    gpg-agent
+case $(arch) in
+    x86_64|amd64)
+    ARCH="amd64";;
+    aarch64|arm64)
+    ARCH="arm64";;
+    *)
+    echo "Unsupported runner OS, aborting CAS Download"  && exit 1;;
+esac
 
-apt-key adv --fetch-keys https://packages.codenotary.org/packages.codenotary.org.gpp.key
-add-apt-repository "deb https://packages.codenotary.org/debian/ stable main"
+CAS_VERSION=$(get_package_version cas)
 
-apt-get update 
-apt-get install -y --no-install-recommends \
-    cas \
+curl -fLs \
+"https://github.com/codenotary/cas/releases/download/v1.0.2/cas-v${CAS_VERSION}-linux-${ARCH}.tar.xz" \
+--output ./cas
 
-rm -rf /var/lib/apt/lists/*
+mv -f "./cas" "/usr/local/bin/cas"
+rm -f "./cas"
