WSL2 fixes

diff --git a/common/rootfs_supervisor/etc/supervisor_scripts/common b/common/rootfs_supervisor/etc/supervisor_scripts/common
--- a/common/rootfs_supervisor/etc/supervisor_scripts/common
+++ b/common/rootfs_supervisor/etc/supervisor_scripts/common
@@ -11,10 +11,10 @@ function start_docker() {
     local starttime
     local endtime
 
-    if grep -q 'microsoft-standard|standard-WSL' /proc/version; then
+    if grep -q 'microsoft-standard\|standard-WSL' /proc/version; then
         # The docker daemon does not start when running WSL2 without adjusting iptables
         update-alternatives --set iptables /usr/sbin/iptables-legacy || echo "Fails adjust iptables"
-        update-alternatives --set ip6tables /usr/sbin/iptables-legacy || echo "Fails adjust ip6tables"
+        update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy || echo "Fails adjust ip6tables"
     fi
 
     echo "Starting docker."
